FROM bitnami/minideb:latest
ARG TIDB_VERSION
ENV TIDB_VERSION=${TIDB_VERSION:-nightly}
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*


RUN  curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh && ln -s /root/.tiup/bin/tiup /bin/tiup

RUN tiup install tidb:${TIDB_VERSION} pd:${TIDB_VERSION} tikv:${TIDB_VERSION} tiflash:${TIDB_VERSION} playground
COPY config.toml /root/.tiup/config.toml
CMD tiup playground ${TIDB_VERSION} --db.host 0.0.0.0 --db.config /root/.tiup/config.toml
